class Barmenu
{
static String barName;
static double brandPrice1;
static String brandName1;
static double brandPrice2;
static String brandName2;
static double brandPrice3;
static String brandName3;
static double brandPrice4;
static String brandName4;
static double brandPrice5;
static String brandName5;
static double brandPrice6;
static String brandName6;
static double brandPrice7;
static String brandName7;
static double brandPrice8;
static String brandName8;
static double brandPrice9;
static String brandName9;
static double brandPrice10;
static String brandName10;
 public static void main(String[]agrs){
   barName ="Rajani Bar & Restaurant";
   brandPrice1 =3000;
   brandName1 ="Redleabel";
   brandPrice2 =2600;
   brandName2 ="jonywalker";
   brandPrice3 =3500;
   brandName3 ="jack Daniel's";
   brandPrice4 =3200;
   brandName4 ="captain Morgan";
   brandPrice5 =2600;
   brandName5 ="Bacardi";
   brandPrice6 =2800;
   brandName6 ="Royal stag";
   brandPrice7 =2200;
   brandName7 ="Imperial Blue";
   brandPrice8 =3200;
   brandName8 ="Officer's choice ";
   brandPrice9 =2600;
   brandName9 ="McDowell's";
   brandPrice10 =2600;
   brandName10 ="jinro";
System.out.println("-------------------------");
System.out.println("bar name is " +barName);
System.out.println("-------------------------");
System.out.println("        Menu             ");
System.out.println("-------------------------");
System.out.println("brand name1 is " +brandName1 );
System.out.println("brand name1 price is " +brandPrice1);
System.out.println("-------------------------");
System.out.println("brand name2 is " +brandName2);
System.out.println("brand name2 price is " +brandPrice2);
System.out.println("-------------------------");
System.out.println("brand name3 is " +brandName3);
System.out.println("brand name3 price is " +brandPrice3);
System.out.println("-------------------------");
System.out.println("brand name4 is " +brandName4);
System.out.println("brand name4 price is " +brandPrice4);
System.out.println("-------------------------");
System.out.println("brand name5 is " +brandName5);
System.out.println("brand name5 price is " +brandPrice5);
System.out.println("-------------------------");
System.out.println("brand name7 is " +brandName6);
System.out.println("brand name7 price is " +brandPrice6);
System.out.println("-------------------------");
System.out.println("brand name7 is " +brandName7);
System.out.println("brand name7 price is " +brandPrice7);
System.out.println("-------------------------");
System.out.println("brand name8 is " +brandName8);
System.out.println("brand name8 price is " +brandPrice8);
System.out.println("-------------------------");
System.out.println("brand name9 is " +brandName9);
System.out.println("brand name9 price is " +brandPrice9);
System.out.println("-------------------------");
System.out.println("brand name10 is " +brandName10);
System.out.println("brand name10 price is " +brandPrice10);
System.out.println("-------------------------");
          }
}